WSGIDaemonProcess geomet-mapproxy-nightly processes=1 threads=1 python-home=/data/web/geomet-mapproxy-nightly/latest
WSGIScriptAlias /geomet-mapproxy /data/web/geomet-mapproxy-nightly/latest/deploy/nightly/geomet-mapproxy.wsgi process-group=geomet-mapproxy-nightly application-group=%{GLOBAL}

<Location /geomet-mapproxy>
  ProxyPass http://localhost:5091/
  ProxyPassReverse http://localhost:5091/
  Header set Access-Control-Allow-Origin "*"
  Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization"
  Header set Access-Control-Allow-Methods "POST, GET, OPTIONS"
</Location>
