#!/bin/sh
# =================================================================
#
# Author: Tom Kralidis <tom.kralidis@ec.gc.ca>
#
# Copyright (c) 2023 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

export GEOMET_MAPPROXY_LOGGING_LOGLEVEL=DEBUG
export GEOMET_MAPPROXY_LOGGING_LOGFILE=stdout

export GEOMET_MAPPROXY_CACHE_DATA=/data/geomet-mapproxy/cache_data
export GEOMET_MAPPROXY_URL=https://geo.wxod-dev.cmc.ec.gc.ca/geomet-mapproxy
export GEOMET_MAPPROXY_TMP=/tmp

export GEOMET_MAPPROXY_CONFIG=/opt/geomet-mapproxy/conf/geomet-mapproxy-config.yml
export GEOMET_MAPPROXY_CACHE_CONFIG=/opt/geomet-mapproxy/conf/geomet-mapproxy-cache-config.yml

echo "Creating cache directory"
mkdir -p $GEOMET_MAPPROXY_CACHE_DATA
chmod 755 $GEOMET_MAPPROXY_CACHE_DATA

if [ -d $GEOMET_MAPPROXY_CONFIG ]
then
    echo "Configuration $GEOMET_MAPPROXY_CONFIG exists"
else
    geomet-mapproxy config create
fi
